# Generated by Django 3.2.13 on 2023-12-02 12:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=20, unique=True)),
                ('document_name', models.CharField(max_length=20, unique=True)),
                ('document', models.FileField(upload_to='commercial_documents/')),
            ],
        ),
        migrations.CreateModel(
            name='ForeignSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.CharField(max_length=20, unique=True)),
                ('contact_details', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('address', models.TextField()),
                ('street_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+\\d{1,20}$', 'Enter a valid contact number starting with a + sign.')])),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(default=' ', max_length=50)),
                ('description', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('inspection_status', models.BooleanField(default=False)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConerstoneLimmited.foreignsupplier')),
            ],
        ),
        migrations.CreateModel(
            name='ImportDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=20, unique=True)),
                ('document', models.FileField(upload_to='commercial_documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('is_company', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_id', models.CharField(max_length=20, unique=True)),
                ('validation_status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('F', 'Failed')], max_length=1)),
                ('validation_date', models.DateField(auto_now=True)),
                ('validated_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Validate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_id', models.CharField(max_length=20, unique=True)),
                ('validation_status', models.BooleanField(default=False)),
                ('validation_date', models.DateField(auto_now_add=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConerstoneLimmited.goods')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_id', models.CharField(max_length=20, unique=True)),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('transport_status', models.CharField(max_length=20)),
                ('transport_type', models.CharField(max_length=50)),
                ('transport_vehicle', models.CharField(max_length=50)),
                ('transport_company', models.CharField(max_length=100)),
                ('transport_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pickup_address', models.TextField()),
                ('delivery_address', models.TextField()),
                ('assigned_driver', models.CharField(max_length=50)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConerstoneLimmited.goods')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConerstoneLimmited.foreignsupplier')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdPartyFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('third_party_fee_id', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConerstoneLimmited.goods')),
            ],
        ),
        migrations.CreateModel(
            name='TaxPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_id', models.CharField(max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConerstoneLimmited.goods')),
                ('taxpayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(max_length=20, unique=True)),
                ('shipping_method', models.CharField(choices=[('Sea', 'Sea Freight'), ('Air', 'Cargo Plane'), ('Road', 'Road Freight'), ('Rail', 'Rail Freight')], max_length=20)),
                ('port_of_loading', models.CharField(max_length=20)),
                ('number_of_containers', models.PositiveIntegerField()),
                ('port_of_discharge', models.CharField(max_length=20)),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('shipment_status', models.CharField(max_length=20)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConerstoneLimmited.goods')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConerstoneLimmited.foreignsupplier')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_id', models.CharField(max_length=20, unique=True)),
                ('inspection_date', models.DateField(auto_now_add=True)),
                ('inspection_result', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=255)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConerstoneLimmited.goods')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConerstoneLimmited.inspector')),
            ],
        ),
        migrations.CreateModel(
            name='ImportDocumentationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(max_length=20, unique=True)),
                ('validation_status', models.BooleanField(default=False)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConerstoneLimmited.goods')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('order_delivery_date', models.DateField(auto_now_add=True)),
                ('delivery_address', models.TextField()),
                ('recipient_name', models.CharField(max_length=100)),
                ('delivery_status', models.CharField(choices=[('D', 'Deliverd'), ('P', 'Pending'), ('I', 'Transit')], max_length=20)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConerstoneLimmited.goods')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConerstoneLimmited.foreignsupplier')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConerstoneLimmited.transport')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=20, unique=True)),
                ('invoice_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ConerstoneLimmited.deliveryorder')),
                ('goods_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConerstoneLimmited.goods')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConerstoneLimmited.recipient')),
                ('tax_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConerstoneLimmited.taxpayment')),
                ('third_party_fees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConerstoneLimmited.thirdpartyfees')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('zipcode', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
