# Generated by Django 3.2.13 on 2023-12-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConerstoneLimmited', '0002_auto_20231219_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity_type',
            new_name='description',
        ),
    ]
