# Generated by Django 3.1 on 2024-01-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConerstoneLimmited', '0005_auto_20240118_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='transport_cost',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='transport_vehicle',
        ),
        migrations.AlterField(
            model_name='transport',
            name='transport_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transport',
            name='transport_type',
            field=models.CharField(max_length=20),
        ),
    ]
