# Generated by Django 4.2.9 on 2024-01-19 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ConerstoneLimmited', '0007_alter_activity_id_alter_commercialdocument_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdpartyfees',
            name='payer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transport',
            name='transport_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
